APIGW_URL = "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"
DOCUMENTS_URL = "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"
headers = {
    "Content-Type": "application/json",
    "Authorization": "XXXXXXXXXXXXXXXXXXXXXX"
}