# SAM configuration file for jubilee-ekyc-backend
version = 0.1

[default.deploy.parameters]
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-jogi1ykjkuno"
profile = "pasha-eu"
stack_name = "jubilee-ekyc-dev"
region = "eu-west-1"
confirm_changeset = false
capabilities = "CAPABILITY_IAM"
parameter_overrides = []

[jubilee.deploy.parameters]
resolve_s3 = true
profile = "jubilee-ekyc"
stack_name = "jubilee-ekyc-backend"
region = "eu-west-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = []
tags = "map-migrated=\"migATRCXG1PSM\""
