AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: |
  Jubilee eKYC backend

Globals:
  Function:
    Timeout: 5
    MemorySize: 128
    Tracing: Active
    Runtime: python3.11
    Architectures:
      - x86_64
    LoggingConfig:
      LogFormat: JSON
Resources:
  ApiGateway:
    Type: AWS::Serverless::Api
    Properties:
      Name: !Sub
        - ${ResourceName} From Stack ${AWS::StackName}
        - ResourceName: ApiGateway
      Description: Application entry point
      StageName: Prod
      DefinitionBody:
        openapi: '3.0'
        info: {}
        paths:
          /faceliveness:
            post:
              x-amazon-apigateway-integration:
                httpMethod: POST
                type: aws_proxy
                uri: !Sub arn:${AWS::Partition}:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${FaceLivenessFn.Arn}/invocations
              responses: {}
          /uploaddocument:
            post:
              x-amazon-apigateway-integration:
                httpMethod: POST
                type: aws_proxy
                uri: !Sub arn:${AWS::Partition}:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${UploadDocumentFn.Arn}/invocations
              responses: {}
      EndpointConfiguration: REGIONAL
      TracingEnabled: true
      Cors:
        MaxAge: 5
  UploadDocumentFn:
    Type: AWS::Serverless::Function
    Properties:
      Description: Process for handling KYC document upload
      CodeUri: process/functions/updloaddocument/src
      Handler: app.handler
      Environment:
        Variables:
          DOCUMENTSUPLOAD_BUCKET_NAME: !Ref DocumentsUpload
          DOCUMENTSUPLOAD_BUCKET_ARN: !GetAtt DocumentsUpload.Arn
          NEWDOCUMENTREGISTRATION_STATE_MACHINE_NAME: !GetAtt NewDocumentRegistration.Name
          NEWDOCUMENTREGISTRATION_STATE_MACHINE_ARN: !Ref NewDocumentRegistration
      Events:
        ApiGatewayPOSTuploaddocument:
          Type: Api
          Properties:
            Path: /uploaddocument
            Method: POST
            RestApiId: !Ref ApiGateway
      Policies:
        - Statement:
            - Effect: Allow
              Action:
                - s3:GetObject
                - s3:GetObjectAcl
                - s3:GetObjectLegalHold
                - s3:GetObjectRetention
                - s3:GetObjectTorrent
                - s3:GetObjectVersion
                - s3:GetObjectVersionAcl
                - s3:GetObjectVersionForReplication
                - s3:GetObjectVersionTorrent
                - s3:ListBucket
                - s3:ListBucketMultipartUploads
                - s3:ListBucketVersions
                - s3:ListMultipartUploadParts
                - s3:AbortMultipartUpload
                - s3:DeleteObject
                - s3:DeleteObjectVersion
                - s3:PutObject
                - s3:PutObjectLegalHold
                - s3:PutObjectRetention
                - s3:RestoreObject
              Resource:
                - !Sub arn:${AWS::Partition}:s3:::${DocumentsUpload}
                - !Sub arn:${AWS::Partition}:s3:::${DocumentsUpload}/*
        - StepFunctionsExecutionPolicy:
            StateMachineName: !GetAtt NewDocumentRegistration.Name
  UploadDocumentFunctionLn:
    Type: AWS::Logs::LogGroup
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties:
      LogGroupName: !Sub /aws/lambda/${UploadDocumentFn}
      RetentionInDays: 30
  FaceLivenessFn:
    Type: AWS::Serverless::Function
    Properties:
      Description: Process for checking faceliveness
      CodeUri: process/functions/faceliveness/src
      Handler: app.handler
      Environment:
        Variables:
          FACELIVENESSRESULTS_TABLE_NAME: !Ref FaceLivenessResults
          FACELIVENESSRESULTS_TABLE_ARN: !GetAtt FaceLivenessResults.Arn
          FACE_LIVENESS_CONFIDENCE_THRESHOLD: 95
      Events:
        ApiGatewayPOSTfaceliveness:
          Type: Api
          Properties:
            Path: /faceliveness
            Method: POST
            RestApiId: !Ref ApiGateway
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref FaceLivenessResults
  FaceLivenessFnLogGroup:
    Type: AWS::Logs::LogGroup
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties:
      LogGroupName: !Sub /aws/lambda/${FaceLivenessFn}
      RetentionInDays: 30
  IPRSSearchFn:
    Type: AWS::Serverless::Function
    Properties:
      Description: IPRS Identity Verification Process
      CodeUri: core/functions/iprs_search/src
      Handler: app.handler
      Environment: {}
      Layers:
        - !Ref JubileeESBAPILayer
  IPRSSearchFnLogGroup:
    Type: AWS::Logs::LogGroup
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties:
      LogGroupName: !Sub /aws/lambda/${IPRSSearchFn}
      RetentionInDays: 30
  KRAValidateIDNumberFn:
    Type: AWS::Serverless::Function
    Properties:
      Description: KRA TAX compliace check
      CodeUri: core/functions/kra_validate_id_number/src
      Handler: app.handler
      Environment: {}
      Layers:
        - !Ref JubileeESBAPILayer
  KRAValidateIDNumberFnLogGroup:
    Type: AWS::Logs::LogGroup
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties:
      LogGroupName: !Sub /aws/lambda/${KRAValidateIDNumberFn}
      RetentionInDays: 30
  LexisNexisSearchRecordFn:
    Type: AWS::Serverless::Function
    Properties:
      Description: LexisNexis Background Checks
      CodeUri: core/functions/lexisnexis_search_record/src
      Handler: app.handler
      Environment: {}
      Layers:
        - !Ref JubileeESBAPILayer
  LexisNexisSearchRecordFnLogGroup:
    Type: AWS::Logs::LogGroup
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties:
      LogGroupName: !Sub /aws/lambda/${LexisNexisSearchRecordFn}
      RetentionInDays: 30
  DocumentTextract:
    Type: AWS::Serverless::Function
    Properties:
      Description: Extract of form fields from documents
      CodeUri: core/functions/document_textract/src
      Handler: app.handler
      Environment: {}
  DocumentTextractLogGroup:
    Type: AWS::Logs::LogGroup
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties:
      LogGroupName: !Sub /aws/lambda/${DocumentTextract}
      RetentionInDays: 30
  FaceLivenessResults:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: session_id
          AttributeType: S
      BillingMode: PAY_PER_REQUEST
      KeySchema:
        - AttributeName: session_id
          KeyType: HASH
      StreamSpecification:
        StreamViewType: NEW_AND_OLD_IMAGES
  DocumentsUpload:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub ${AWS::StackName}-documents-${AWS::AccountId}
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: aws:kms
              KMSMasterKeyID: alias/aws/s3
      PublicAccessBlockConfiguration:
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
  DocumentsUploadBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref DocumentsUpload
      PolicyDocument:
        Id: RequireEncryptionInTransit
        Version: '2012-10-17'
        Statement:
          - Principal: '*'
            Action: '*'
            Effect: Deny
            Resource:
              - !GetAtt DocumentsUpload.Arn
              - !Sub ${DocumentsUpload.Arn}/*
            Condition:
              Bool:
                aws:SecureTransport: 'false'
  NewDocumentRegistrationStateMachineRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: states.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AWSXrayWriteOnlyAccess
        - arn:aws:iam::aws:policy/CloudWatchLogsFullAccess
      Policies:
        - PolicyName: StepFunctionsDescribeAndStopExecution
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - states:DescribeExecution
                  - states:StopExecution
                Resource: '*'
        - PolicyName: StepFunctionsEventBridgePolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - events:PutRule
                  - events:PutTargets
                  - events:DeleteRule
                  - events:RemoveTargets
                  - events:DescribeRule
                Resource:
                  - !Sub arn:aws:events:${AWS::Region}:${AWS::AccountId}:rule/StepFunctionsGetEventsForStepFunctionsExecutionRule*
  NewDocumentRegistration:
    Type: AWS::Serverless::StateMachine
    Properties:
      Role: !GetAtt NewDocumentRegistrationStateMachineRole.Arn
      Definition:
        StartAt: DocumentExtraction
        States:
          DocumentExtraction:
            Type: Task
            Resource: arn:aws:states:::states:startExecution.sync:2
            Parameters:
              StateMachineArn: ${DocumentExtractArn}
              Input:
                StatePayload: Hello from Step Functions!
                AWS_STEP_FUNCTIONS_STARTED_BY_EXECUTION_ID.$: $$.Execution.Id
            Next: SearchIPRS
          SearchIPRS:
            Type: Task
            Resource: arn:aws:states:::lambda:invoke
            OutputPath: $.Payload
            Parameters:
              Payload.$: $
              FunctionName: ${IPRSIdentityVerificationArn}
            Retry:
              - ErrorEquals:
                  - Lambda.ServiceException
                  - Lambda.AWSLambdaException
                  - Lambda.SdkClientException
                  - Lambda.TooManyRequestsException
                IntervalSeconds: 1
                MaxAttempts: 3
                BackoffRate: 2
            Next: Parallel
          Parallel:
            Type: Parallel
            Branches:
              - StartAt: LexisNexisSearchRecord
                States:
                  LexisNexisSearchRecord:
                    Type: Task
                    Resource: arn:aws:states:::lambda:invoke
                    OutputPath: $.Payload
                    Parameters:
                      Payload.$: $
                      FunctionName: ${LexisNexisBackgroundChecksArn}
                    Retry:
                      - ErrorEquals:
                          - Lambda.ServiceException
                          - Lambda.AWSLambdaException
                          - Lambda.SdkClientException
                          - Lambda.TooManyRequestsException
                        IntervalSeconds: 1
                        MaxAttempts: 3
                        BackoffRate: 2
                    End: true
              - StartAt: KRAValidateIDNumberFn
                States:
                  KRAValidateIDNumberFn:
                    Type: Task
                    Resource: arn:aws:states:::lambda:invoke
                    OutputPath: $.Payload
                    Parameters:
                      Payload.$: $
                      FunctionName: ${KRATaxComplianceVerificationArn}
                    Retry:
                      - ErrorEquals:
                          - Lambda.ServiceException
                          - Lambda.AWSLambdaException
                          - Lambda.SdkClientException
                          - Lambda.TooManyRequestsException
                        IntervalSeconds: 1
                        MaxAttempts: 3
                        BackoffRate: 2
                    End: true
            End: true
      Logging:
        Level: ALL
        IncludeExecutionData: true
        Destinations:
          - CloudWatchLogsLogGroup:
              LogGroupArn: !GetAtt NewDocumentRegistrationLogGroup.Arn
      Tracing:
        Enabled: true
      Type: STANDARD
      DefinitionSubstitutions:
        DocumentExtractArn: !GetAtt DocumentExtract.Arn
        KRATaxComplianceVerificationArn: !Ref KRAValidateIDNumberFn
        IPRSIdentityVerificationArn: !Ref IPRSSearchFn
        LexisNexisBackgroundChecksArn: !Ref LexisNexisSearchRecordFn

  NewDocumentRegistrationLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub
        - /aws/vendedlogs/states/${AWS::StackName}-${ResourceId}-Logs
        - ResourceId: NewDocumentRegistration
  DocumentExtract:
    Type: AWS::Serverless::StateMachine
    Properties:
      Definition:
        StartAt: LambdaTask
        States:
          LambdaTask:
            Type: Task
            Resource: arn:aws:states:::lambda:invoke
            Parameters:
              Payload.$: $
              FunctionName: ${LambdaFunction1}
            End: true
      Logging:
        Level: ALL
        IncludeExecutionData: true
        Destinations:
          - CloudWatchLogsLogGroup:
              LogGroupArn: !GetAtt DocumentExtractLogGroup.Arn
      Policies:
        - AWSXrayWriteOnlyAccess
        - Statement:
            - Effect: Allow
              Action:
                - logs:CreateLogDelivery
                - logs:GetLogDelivery
                - logs:UpdateLogDelivery
                - logs:DeleteLogDelivery
                - logs:ListLogDeliveries
                - logs:PutResourcePolicy
                - logs:DescribeResourcePolicies
                - logs:DescribeLogGroups
              Resource: '*'
        - LambdaInvokePolicy:
            FunctionName: !Ref DocumentTextract
      Tracing:
        Enabled: true
      Type: EXPRESS
      DefinitionSubstitutions:
        LambdaFunction1: !GetAtt DocumentTextract.Arn
  DocumentExtractLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub
        - /aws/vendedlogs/states/${AWS::StackName}-${ResourceId}-Logs
        - ResourceId: DocumentExtract
  JubileeESBAPILayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      Description: !Sub
        - Stack ${AWS::StackName} Layer ${ResourceName}
        - ResourceName: JubileeESBAPILayer
      ContentUri: core/layers/jubilee_esb_api_layer/src
      RetentionPolicy: Retain
    Metadata:
      BuildMethod: python3.11
Metadata:
  AWS::Composer::Groups:
    Group:
      Label: 'Layer1: API Gateway'
      Members:
        - ApiGateway
    Group2:
      Label: 'Layer2: Process orchestration'
      Members:
        - FaceLivenessFn
        - UploadDocumentFn
        - NewDocumentRegistration
        - DocumentsUpload
        - FaceLivenessResults
    Group3:
      Label: 'Layer3a: KYC Capture'
      Members:
        - DocumentExtract
    Group4:
      Label: 'Layer3b: KYC Validation'
      Members:
        - IPRSSearchFn
        - LexisNexisSearchRecordFn
        - KRAValidateIDNumberFn
        - JubileeESBAPILayer