AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: |
  Jubilee eKYC backend

Parameters:
  AmplifyS3BucketName:
    Type: String
    Default: amplify-d2896e60a8d7f8-ma-kycdocumentsbucketa4bf11-aae1vuopf1xq
    Description: Name of the Amplify S3 bucket where KYC documents are upload into by portal

  JubileeESBAPICredentials:
    Type: String
    Default: '{"username":"your-username","password":"your-password","business":"your-business","baseurl":"https://example.com"}'
    NoEcho: true
    Description: Jubilee ESB API Credentials in Secrets Manager
  PortalGraphQLCredentials:
    Type: String
    Default: '{"api_key":"graphql-api-key","url":"https://example.com"}'
    NoEcho: true
    Description: Port app-sync graphql credentials
Globals:
  Function:
    Timeout: 300
    MemorySize: 128
    Tracing: Active
    Runtime: python3.11
    Architectures:
      - x86_64
    LoggingConfig:
      LogFormat: JSON
Resources:
  JubileeESBAPISecret:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: !Sub ${AWS::StackName}-jubilee-esb-ApiGateway-credentials
      Description: Jubilee ESB API Credentials
      SecretString: !Ref JubileeESBAPICredentials
  PortalGraphQLSecret:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: !Sub ${AWS::StackName}-portal-graphql-credentials
      Description: Portal GraphQL API Credentials
      SecretString: !Ref PortalGraphQLCredentials
  ApiGateway:
    Type: AWS::Serverless::Api
    Properties:
      Name: !Sub
        - ${ResourceName} From Stack ${AWS::StackName}
        - ResourceName: ApiGateway
      StageName: Prod
      DefinitionBody: !Transform
        Name: AWS::Include
        Parameters:
          Location: openapi.yaml
      EndpointConfiguration: REGIONAL
      TracingEnabled: true
      Cors:
        AllowOrigin: '''https://main.d2896e60a8d7f8.amplifyapp.com'''
        AllowHeaders: '''Content-Type, Authorization, X-Api-Key, X-Amz-Date,
          X-Amz-Security-Token'''
        AllowMethods: '''POST, OPTIONS'''
        MaxAge: 60

  RegistrationFn:
    Type: AWS::Serverless::Function
    Properties:
      Description: Handles agent and customer registration
      CodeUri: process/functions/registration/src
      Handler: app.handler
      Environment:
        Variables:
          PORTAL_GRAPHQL_SECRET_ARN: !Ref PortalGraphQLSecret
      Events:
        ApiGatewayPOSTAgentRegistration:
          Type: Api
          Properties:
            Path: /agent-registration
            Method: POST
            RestApiId: !Ref ApiGateway
        ApiGatewayPOSTCustomerRegistration:
          Type: Api
          Properties:
            Path: /customer-registration
            Method: POST
            RestApiId: !Ref ApiGateway
      Policies:
        - AWSLambdaBasicExecutionRole
        - Statement:
            - Effect: Allow
              Action:
                - secretsmanager:GetSecretValue
              Resource:
                - !Ref PortalGraphQLSecret
      Layers:
        - !Ref PortalProjectionLayer

  RegistrationFnLogGroup:
    Type: AWS::Logs::LogGroup
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties:
      LogGroupName: !Sub /aws/lambda/${RegistrationFn}
      RetentionInDays: 30
  DocumentValidationFn:
    Type: AWS::Serverless::Function
    Properties:
      Description: Handles validating that uploaded documents match the provided data
      CodeUri: process/functions/document_validation/src
      Handler: app.handler
      Environment:
        Variables:
          KYCDOCUMENTSBUCKET_NAME: !Ref KYCDocumentsBucket
          KYCDOCUMENTSBUCKET_ARN: !GetAtt KYCDocumentsBucket.Arn
          AMPLIFY_S3_BUCKET_NAME: !Ref AmplifyS3BucketName
          PORTAL_GRAPHQL_SECRET_ARN: !Ref PortalGraphQLSecret
      Events:
        ApiGatewayPOSTKRA:
          Type: Api
          Properties:
            Path: /document/kra-validation
            Method: POST
            RestApiId: !Ref ApiGateway
        ApiGatewayPOSTID:
          Type: Api
          Properties:
            Path: /document/nationalid-validation
            Method: POST
            RestApiId: !Ref ApiGateway
        ApiGatewayPOSTPassport:
          Type: Api
          Properties:
            Path: /document/passport-validation
            Method: POST
            RestApiId: !Ref ApiGateway
        ApiGatewayPOSTCompany:
          Type: Api
          Properties:
            Path: /document/company-validation
            Method: POST
            RestApiId: !Ref ApiGateway
      Policies:
        - Statement:
            - Effect: Allow
              Action:
                - secretsmanager:GetSecretValue
              Resource:
                - !Ref PortalGraphQLSecret
        - AWSLambdaBasicExecutionRole
        - Statement:
            - Effect: Allow
              Action:
                - s3:GetObject
                - s3:GetObjectAcl
                - s3:GetObjectLegalHold
                - s3:GetObjectRetention
                - s3:GetObjectTorrent
                - s3:GetObjectVersion
                - s3:GetObjectVersionAcl
                - s3:GetObjectVersionForReplication
                - s3:GetObjectVersionTorrent
                - s3:ListBucket
                - s3:ListBucketMultipartUploads
                - s3:ListBucketVersions
                - s3:ListMultipartUploadParts
                - s3:AbortMultipartUpload
                - s3:DeleteObject
                - s3:DeleteObjectVersion
                - s3:PutObject
                - s3:PutObjectLegalHold
                - s3:PutObjectRetention
                - s3:RestoreObject
              Resource:
                - !Sub arn:${AWS::Partition}:s3:::${KYCDocumentsBucket}
                - !Sub arn:${AWS::Partition}:s3:::${KYCDocumentsBucket}/*
        - Statement:
            - Effect: Allow
              Action:
                - s3:GetObject
                - s3:GetObjectVersion
                - s3:ListBucket
                - s3:ListBucketVersions
              Resource:
                - !Sub arn:${AWS::Partition}:s3:::${AmplifyS3BucketName}
                - !Sub arn:${AWS::Partition}:s3:::${AmplifyS3BucketName}/*
        - Statement:
            - Effect: Allow
              Action:
                - textract:AnalyzeDocument
                - textract:DetectDocumentText
                - textract:GetDocumentAnalysis
                - textract:GetDocumentTextDetection
              Resource: '*'
      Layers:
        - !Ref PortalProjectionLayer
        - !Ref DocumentTextractLayer
  DocumentValidationFnLogGroup:
    Type: AWS::Logs::LogGroup
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties:
      LogGroupName: !Sub /aws/lambda/${DocumentValidationFn}
      RetentionInDays: 30
  GovernmentVerificationFn:
    Type: AWS::Serverless::Function
    Properties:
      Description: Handles calls to external government services (IPRS) for data
        verification
      CodeUri: process/functions/government_verification/src
      Handler: app.handler
      Environment:
        Variables:
          PORTAL_GRAPHQL_SECRET_ARN: !Ref PortalGraphQLSecret
          JUBILEE_ESB_API_SECRET_ARN: !Ref JubileeESBAPISecret
      Events:
        ApiGatewayPOSTKRA:
          Type: Api
          Properties:
            Path: /government/kra-verification
            Method: POST
            RestApiId: !Ref ApiGateway
        ApiGatewayPOSTID:
          Type: Api
          Properties:
            Path: /government/nationalid-verification
            Method: POST
            RestApiId: !Ref ApiGateway
        ApiGatewayPOSTPassport:
          Type: Api
          Properties:
            Path: /government/passport-verification
            Method: POST
            RestApiId: !Ref ApiGateway
        ApiGatewayPOSTCompany:
          Type: Api
          Properties:
            Path: /government/company-verification
            Method: POST
            RestApiId: !Ref ApiGateway
      Policies:
        - AWSLambdaBasicExecutionRole
        - Statement:
            - Effect: Allow
              Action:
                - secretsmanager:GetSecretValue
              Resource:
                - !Ref PortalGraphQLSecret
                - !Ref JubileeESBAPISecret
      Layers:
        - !Ref PortalProjectionLayer
  GovernmentVerificationFnLogGroup:
    Type: AWS::Logs::LogGroup
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties:
      LogGroupName: !Sub /aws/lambda/${GovernmentVerificationFn}
      RetentionInDays: 30
  BackgroundChecksFn:
    Type: AWS::Serverless::Function
    Properties:
      Description: Handles background checking against Lexis Nexis API
      CodeUri: process/functions/background_check/src
      Handler: app.lambda_handler
      Environment:
        Variables:
          PORTAL_GRAPHQL_SECRET_ARN: !Ref PortalGraphQLSecret
          JUBILEE_ESB_API_SECRET_ARN: !Ref JubileeESBAPISecret
      Events:
        ApiGatewayPOSTBackgroundCheck:
          Type: Api
          Properties:
            Path: /backgroundcheck
            Method: POST
            RestApiId: !Ref ApiGateway
      Policies:
        - AWSLambdaBasicExecutionRole
        - Statement:
            - Effect: Allow
              Action:
                - secretsmanager:GetSecretValue
              Resource:
                - !Ref PortalGraphQLSecret
                - !Ref JubileeESBAPISecret
      Layers:
        - !Ref PortalProjectionLayer
  BackgroundChecksFnLogGroup:
    Type: AWS::Logs::LogGroup
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties:
      LogGroupName: !Sub /aws/lambda/${BackgroundChecksFn}
      RetentionInDays: 30
  FaceLivenessFn:
    Type: AWS::Serverless::Function
    Properties:
      Handler: app.handler
      Environment:
        Variables:
          FACELIVENESSRESULTS_TABLE_NAME: !Ref FaceLivenessResults
          FACELIVENESSRESULTS_TABLE_ARN: !GetAtt FaceLivenessResults.Arn
          FACE_LIVENESS_CONFIDENCE_THRESHOLD: 95
      Policies:
        - Statement:
            - Effect: Allow
              Action:
                - secretsmanager:GetSecretValue
              Resource:
                - !Ref PortalGraphQLSecret
        - DynamoDBCrudPolicy:
            TableName: !Ref FaceLivenessResults
        - Statement:
            - Effect: Allow
              Action:
                - rekognition:CreateFaceLivenessSession
                - rekognition:GetFaceLivenessSessionResults
              Resource: '*'
      Layers:
        - !Ref PortalProjectionLayer
      Events:
        ApiGatewayPOSTfaceliveness:
          Type: Api
          Properties:
            Path: /faceliveness
            Method: POST
            RestApiId: !Ref ApiGateway
  FaceLivenessFnLogGroup:
    Type: AWS::Logs::LogGroup
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties:
      LogGroupName: !Sub /aws/lambda/${FaceLivenessFn}
      RetentionInDays: 30
  FaceLivenessResults:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: session_id
          AttributeType: S
      BillingMode: PAY_PER_REQUEST
      KeySchema:
        - AttributeName: session_id
          KeyType: HASH
      StreamSpecification:
        StreamViewType: NEW_AND_OLD_IMAGES
  DocumentTextractLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      Description: Textract Layer
      ContentUri: core/layers/document_textract/src
      RetentionPolicy: Retain
    Metadata:
      BuildMethod: python3.11
  JubileeESBAPILayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      Description: Jubilee ESB API Layer
      ContentUri: core/layers/jubilee_esb_api_layer/src
      RetentionPolicy: Retain
    Metadata:
      BuildMethod: python3.11
  PortalProjectionLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      Description: Projecting backend events into portal using graphql
      ContentUri: shared/portal_project/src
      RetentionPolicy: Retain
    Metadata:
      BuildMethod: python3.11
  KYCDocumentsBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub ${AWS::StackName}-kycdocume-${AWS::AccountId}
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: aws:kms
              KMSMasterKeyID: alias/aws/s3
      PublicAccessBlockConfiguration:
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
  KYCDocumentsBucketBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref KYCDocumentsBucket
      PolicyDocument:
        Id: RequireEncryptionInTransit
        Version: '2012-10-17'
        Statement:
          - Principal: '*'
            Action: '*'
            Effect: Deny
            Resource:
              - !GetAtt KYCDocumentsBucket.Arn
              - !Sub ${KYCDocumentsBucket.Arn}/*
            Condition:
              Bool:
                aws:SecureTransport: 'false'
Metadata:
  AWS::Composer::Groups:
    Group2:
      Label: 'Layer2: Process orchestration'
      Members:
        - GovernmentVerificationFn
        - DocumentValidationFn
        - FaceLivenessFn
        - FaceLivenessResults
        - KYCDocumentsBucket
        - RegistrationFn
        - Function
Outputs:
  ApiGatewayUrl:
    Description: API Gateway Production URL
    Value: !Sub https://${ApiGateway}.execute-api.${AWS::Region}.amazonaws.com/Prod
  FaceLivenessFnLogGroup:
    Description: Tailing the Facelivess Logs
    Value: FaceLivenessFnLogGroup
  DocumentValidationFnLogGroup:
    Description: Tailing the upload document GW endpoint Logs
    Value: DocumentValidationFnLogGroup
  DocumentTextractFn:
    Description: Tailing the document textract lambda logs
    Value: DocumentTextractFnLogGroup