AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: |
  Jubilee eKYC backend

Globals:
  Function:
    Timeout: 5
    MemorySize: 128
    Tracing: Active
    Runtime: python3.11
    Architectures:
      - x86_64
    LoggingConfig:
      LogFormat: JSON
Resources:
  ApiGateway:
    Type: AWS::Serverless::Api
    Properties:
      Name: !Sub
        - ${ResourceName} From Stack ${AWS::StackName}
        - ResourceName: ApiGateway
      Description: Application entry point
      StageName: Prod
      DefinitionBody:
        openapi: '3.0'
        info: {}
        paths:
          /faceliveness:
            post:
              x-amazon-apigateway-integration:
                httpMethod: POST
                type: aws_proxy
                uri: !Sub arn:${AWS::Partition}:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${FaceLivenessFunction.Arn}/invocations
              responses: {}
          /uploaddocument:
            post:
              x-amazon-apigateway-integration:
                httpMethod: POST
                type: aws_proxy
                uri: !Sub arn:${AWS::Partition}:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${UploadDocumentFunction.Arn}/invocations
              responses: {}
      EndpointConfiguration: REGIONAL
      TracingEnabled: true
      Cors:
        MaxAge: 5
  UploadDocumentFunction:
    Type: AWS::Serverless::Function
    Properties:
      Description: Process for handling KYC document upload
      CodeUri: process/functions/updloaddocument/src
      Handler: app.handler
      Environment:
        Variables:
          DOCUMENTSUPLOAD_BUCKET_NAME: !Ref DocumentsUpload
          DOCUMENTSUPLOAD_BUCKET_ARN: !GetAtt DocumentsUpload.Arn
          NEWDOCUMENTREGISTRATION_STATE_MACHINE_NAME: !GetAtt NewDocumentRegistration.Name
          NEWDOCUMENTREGISTRATION_STATE_MACHINE_ARN: !Ref NewDocumentRegistration
      Events:
        ApiGatewayPOSTuploaddocument:
          Type: Api
          Properties:
            Path: /uploaddocument
            Method: POST
            RestApiId: !Ref ApiGateway
      Policies:
        - Statement:
            - Effect: Allow
              Action:
                - s3:GetObject
                - s3:GetObjectAcl
                - s3:GetObjectLegalHold
                - s3:GetObjectRetention
                - s3:GetObjectTorrent
                - s3:GetObjectVersion
                - s3:GetObjectVersionAcl
                - s3:GetObjectVersionForReplication
                - s3:GetObjectVersionTorrent
                - s3:ListBucket
                - s3:ListBucketMultipartUploads
                - s3:ListBucketVersions
                - s3:ListMultipartUploadParts
                - s3:AbortMultipartUpload
                - s3:DeleteObject
                - s3:DeleteObjectVersion
                - s3:PutObject
                - s3:PutObjectLegalHold
                - s3:PutObjectRetention
                - s3:RestoreObject
              Resource:
                - !Sub arn:${AWS::Partition}:s3:::${DocumentsUpload}
                - !Sub arn:${AWS::Partition}:s3:::${DocumentsUpload}/*
        - StepFunctionsExecutionPolicy:
            StateMachineName: !GetAtt NewDocumentRegistration.Name
  UploadDocumentFunctionLogGroup:
    Type: AWS::Logs::LogGroup
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties:
      LogGroupName: !Sub /aws/lambda/${UploadDocumentFunction}
      RetentionInDays: 30
  FaceLivenessFunction:
    Type: AWS::Serverless::Function
    Properties:
      Description: Process for checking faceliveness
      CodeUri: process/functions/faceliveness/src
      Handler: app.handler
      Environment:
        Variables:
          FACELIVENESSRESULTS_TABLE_NAME: !Ref FaceLivenessResults
          FACELIVENESSRESULTS_TABLE_ARN: !GetAtt FaceLivenessResults.Arn
          FACE_LIVENESS_CONFIDENCE_THRESHOLD: 95
      Events:
        ApiGatewayPOSTfaceliveness:
          Type: Api
          Properties:
            Path: /faceliveness
            Method: POST
            RestApiId: !Ref ApiGateway
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref FaceLivenessResults
  FaceLivenessFunctionLogGroup:
    Type: AWS::Logs::LogGroup
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties:
      LogGroupName: !Sub /aws/lambda/${FaceLivenessFunction}
      RetentionInDays: 30
  IPRSIdentityVerificationFunction:
    Type: AWS::Serverless::Function
    Properties:
      Description: IPRS Identity Verification Process
      CodeUri: core/functions/iprsidentityverification/src
      Handler: app.handler
      Environment: {}
  IPRSIdentityVerificationFunctionLogGroup:
    Type: AWS::Logs::LogGroup
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties:
      LogGroupName: !Sub /aws/lambda/${IPRSIdentityVerificationFunction}
      RetentionInDays: 30
  KRATaxComplianceVerificationFunction:
    Type: AWS::Serverless::Function
    Properties:
      Description: KRA TAX compliace check
      CodeUri: core/functions/krataxcomplianceverification/src
      Handler: app.handler
      Environment: {}
  KRATaxComplianceVerificationFunctionLogGroup:
    Type: AWS::Logs::LogGroup
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties:
      LogGroupName: !Sub /aws/lambda/${KRATaxComplianceVerificationFunction}
      RetentionInDays: 30
  LexisNexisBackgroundChecksFunction:
    Type: AWS::Serverless::Function
    Properties:
      Description: LexisNexis Background Checks
      CodeUri: core/functions/lexisnexisbackgroundchecks/src
      Handler: app.handler
      Environment: {}
  LexisNexisBackgroundChecksFunctionLogGroup:
    Type: AWS::Logs::LogGroup
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties:
      LogGroupName: !Sub /aws/lambda/${LexisNexisBackgroundChecksFunction}
      RetentionInDays: 30
  DocumentExtractFunction:
    Type: AWS::Serverless::Function
    Properties:
      Description: Extract of form fields from documents
      CodeUri: core/functions/documentextract/src
      Handler: app.handler
      Environment: {}
  DocumentExtractFunctionLogGroup:
    Type: AWS::Logs::LogGroup
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties:
      LogGroupName: !Sub /aws/lambda/${DocumentExtractFunction}
      RetentionInDays: 30
  FaceLivenessResults:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: session_id
          AttributeType: S
      BillingMode: PAY_PER_REQUEST
      KeySchema:
        - AttributeName: session_id
          KeyType: HASH
      StreamSpecification:
        StreamViewType: NEW_AND_OLD_IMAGES
  DocumentsUpload:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub ${AWS::StackName}-documents-${AWS::AccountId}
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: aws:kms
              KMSMasterKeyID: alias/aws/s3
      PublicAccessBlockConfiguration:
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
  DocumentsUploadBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref DocumentsUpload
      PolicyDocument:
        Id: RequireEncryptionInTransit
        Version: '2012-10-17'
        Statement:
          - Principal: '*'
            Action: '*'
            Effect: Deny
            Resource:
              - !GetAtt DocumentsUpload.Arn
              - !Sub ${DocumentsUpload.Arn}/*
            Condition:
              Bool:
                aws:SecureTransport: 'false'
  NewDocumentRegistrationStateMachineRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: states.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AWSXrayWriteOnlyAccess
        - arn:aws:iam::aws:policy/CloudWatchLogsFullAccess
      Policies:
        - PolicyName: StepFunctionsExecutionPolicy-IPRS
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action: states:StartExecution
                Resource: !GetAtt IPRSIdentityVerification.Arn
        - PolicyName: StepFunctionsExecutionPolicy-LexisNexis
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action: states:StartExecution
                Resource: !GetAtt LexisNexisBackgroundChecks.Arn
        - PolicyName: StepFunctionsExecutionPolicy-Safaricom
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action: states:StartExecution
                Resource: !GetAtt SafaricomPhoneVerification.Arn
        - PolicyName: StepFunctionsDescribeAndStopExecution
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - states:DescribeExecution
                  - states:StopExecution
                Resource: '*'
        - PolicyName: StepFunctionsEventBridgePolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - events:PutRule
                  - events:PutTargets
                  - events:DeleteRule
                  - events:RemoveTargets
                  - events:DescribeRule
                Resource:
                  - !Sub arn:aws:events:${AWS::Region}:${AWS::AccountId}:rule/StepFunctionsGetEventsForStepFunctionsExecutionRule*
  NewDocumentRegistration:
    Type: AWS::Serverless::StateMachine
    Properties:
      Role: !GetAtt NewDocumentRegistrationStateMachineRole.Arn
      Definition:
        StartAt: DocumentExtraction
        States:
          DocumentExtraction:
            Type: Task
            Resource: arn:aws:states:::states:startExecution.sync:2
            Parameters:
              StateMachineArn: ${DocumentExtractArn}
              Input:
                StatePayload: Hello from Step Functions!
                AWS_STEP_FUNCTIONS_STARTED_BY_EXECUTION_ID.$: $$.Execution.Id
            Next: DocumentValidation
          DocumentValidation:
            Type: Parallel
            Branches:
              - StartAt: IPRSIdentityVerification
                States:
                  IPRSIdentityVerification:
                    Type: Task
                    Resource: arn:aws:states:::states:startExecution.sync:2
                    Parameters:
                      StateMachineArn: ${IPRSIdentityVerificationArn}
                      Input:
                        StatePayload: Hello from Step Functions!
                        AWS_STEP_FUNCTIONS_STARTED_BY_EXECUTION_ID.$: $$.Execution.Id
                    End: true
              - StartAt: KRATaxComplianceVerification
                States:
                  KRATaxComplianceVerification:
                    Type: Task
                    Resource: arn:aws:states:::states:startExecution.sync:2
                    Parameters:
                      StateMachineArn: ${KRATaxComplianceVerificationArn}
                      Input:
                        StatePayload: Hello from Step Functions!
                        AWS_STEP_FUNCTIONS_STARTED_BY_EXECUTION_ID.$: $$.Execution.Id
                    End: true
              - StartAt: LexisNexisBackgroundChecks
                States:
                  LexisNexisBackgroundChecks:
                    Type: Task
                    Resource: arn:aws:states:::states:startExecution.sync:2
                    Parameters:
                      StateMachineArn: ${LexisNexisBackgroundChecksArn}
                      Input:
                        StatePayload: Hello from Step Functions!
                        AWS_STEP_FUNCTIONS_STARTED_BY_EXECUTION_ID.$: $$.Execution.Id
                    End: true
            End: true
      Logging:
        Level: ALL
        IncludeExecutionData: true
        Destinations:
          - CloudWatchLogsLogGroup:
              LogGroupArn: !GetAtt NewDocumentRegistrationLogGroup.Arn
      Tracing:
        Enabled: true
      Type: STANDARD
      DefinitionSubstitutions:
        DocumentExtractArn: !GetAtt DocumentExtract.Arn
        KRATaxComplianceVerificationArn: !Ref AWS::NoValue
        IPRSIdentityVerificationArn: !Ref AWS::NoValue
        LexisNexisBackgroundChecksArn: !Ref AWS::NoValue
        SafaricomPhoneVerificationArn: !Ref AWS::NoValue
  NewDocumentRegistrationLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub
        - /aws/vendedlogs/states/${AWS::StackName}-${ResourceId}-Logs
        - ResourceId: NewDocumentRegistration
  DocumentExtract:
    Type: AWS::Serverless::StateMachine
    Properties:
      Definition:
        StartAt: LambdaTask
        States:
          LambdaTask:
            Type: Task
            Resource: arn:aws:states:::lambda:invoke
            Parameters:
              Payload.$: $
              FunctionName: ${LambdaFunction1}
            End: true
      Logging:
        Level: ALL
        IncludeExecutionData: true
        Destinations:
          - CloudWatchLogsLogGroup:
              LogGroupArn: !GetAtt DocumentExtractLogGroup.Arn
      Policies:
        - AWSXrayWriteOnlyAccess
        - Statement:
            - Effect: Allow
              Action:
                - logs:CreateLogDelivery
                - logs:GetLogDelivery
                - logs:UpdateLogDelivery
                - logs:DeleteLogDelivery
                - logs:ListLogDeliveries
                - logs:PutResourcePolicy
                - logs:DescribeResourcePolicies
                - logs:DescribeLogGroups
              Resource: '*'
        - LambdaInvokePolicy:
            FunctionName: !Ref DocumentExtractFunction
      Tracing:
        Enabled: true
      Type: EXPRESS
      DefinitionSubstitutions:
        LambdaFunction1: !GetAtt DocumentExtractFunction.Arn
  DocumentExtractLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub
        - /aws/vendedlogs/states/${AWS::StackName}-${ResourceId}-Logs
        - ResourceId: DocumentExtract
Metadata:
  AWS::Composer::Groups:
    Group:
      Label: 'Layer1: API Gateway'
      Members:
        - ApiGateway
    Group2:
      Label: 'Layer2: Process orchestration'
      Members:
        - FaceLivenessFunction
        - UploadDocumentFunction
        - NewDocumentRegistration
        - DocumentsUpload
        - FaceLivenessResults
    Group3:
      Label: 'Layer3a: KYC Capture'
      Members:
        - DocumentExtract
    Group4:
      Label: 'Layer3b: KYC Validation'
      Members:
        - IPRSIdentityVerificationFunction
        - KRATaxComplianceVerificationFunction
        - LexisNexisBackgroundChecksFunction